# Название рабочего процесса
name: Create Release Assets with Nuitka

# Триггер: запускать только при публикации нового релиза
on:
  release:
    types: [published]

# Задачи
jobs:
  build-and-upload:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      # 1. Клонируем код репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt

      # 4. Собираем .exe файл с помощью Nuitka
      # ИЗМЕНЕНИЕ: Вся команда написана в ОДНУ СТРОКУ, чтобы избежать ошибок парсинга PowerShell
      - name: Build executable with Nuitka
        run: python -m nuitka --onefile --windows-disable-console --include-package-data=tkinterdnd2 --output-filename="Adlens_xyzconverter" --output-dir=dist xyzconverter.py

      # 5. Создаем ZIP-архив с программой
      - name: Create ZIP from executable
        run: Compress-Archive -Path dist/Adlens_xyzconverter.exe -DestinationPath "Adlens-xyzconverter.zip"

      # 6. Загружаем наш ZIP-файл как ассет к релизу
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: "Adlens-xyzconverter.zip"
