# Название рабочего процесса
name: Create Release Assets with Nuitka

# Триггер: запускать только при публикации нового релиза
on:
  release:
    types: [published]

# Задачи
jobs:
  build-and-upload:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      # 1. Клонируем код репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nuitka
          pip install -r requirements.txt

      # 4. Собираем .exe файл с помощью Nuitka
      # ИЗМЕНЕНИЕ 1: Упрощено имя выходного .exe файла
      - name: Build executable with Nuitka
        run: python -m nuitka --onefile --windows-console-mode=disable --enable-plugin=tk-inter --include-package-data=tkinterdnd2 --assume-yes-for-downloads --output-filename="xyzconverter" --output-dir=dist xyzconverter.py

      # 5. Создаем ZIP-архив с программой
      # ИЗМЕНЕНИЕ 2: Используем новые имена для .exe и .zip
      - name: Create ZIP from executable
        run: Compress-Archive -Path dist/xyzconverter.exe -DestinationPath "xyzconverter.zip"

      # 6. Загружаем наш ZIP-файл как ассет к релизу
      # ИЗМЕНЕНИЕ 3: Указываем новое имя .zip файла для загрузки
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: "xyzconverter.zip"
