# Название рабочего процесса
name: Create Release Assets

# Триггер: запускать только при публикации нового релиза
on:
  release:
    types: [published]

# Задачи
jobs:
  build-and-upload:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      # 1. Клонируем код репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Устанавливаем зависимости
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Устанавливаем PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # 5. Собираем .exe файл
      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --windowed --name "Adlens_xyzconverter" xyzconverter.py

      # 6. Создаем ZIP-архив с программой
      # ИЗМЕНЕНИЕ 1: Используем безопасное имя файла без апострофа
      - name: Create ZIP from executable
        run: Compress-Archive -Path dist/Adlens_xyzconverter.exe -DestinationPath "Adlens-xyzconverter.zip"

      # 7. Загружаем наш ZIP-файл как ассет к релизу
      # ИЗМЕНЕНИЕ 2: Указываем правильное, безопасное имя файла
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: "Adlens-xyzconverter.zip"
