# Название рабочего процесса
name: Create Release Assets

# Триггер: запускать только при публикации нового релиза
on:
  release:
    types: [published]

# Задачи
jobs:
  build-and-upload:
    # Запускаемся на Windows для сборки .exe
    runs-on: windows-latest

    steps:
      # 1. Клонируем код репозитория
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      # 3. Устанавливаем зависимости из requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Устанавливаем PyInstaller
      - name: Install PyInstaller
        run: pip install pyinstaller

      # 5. Собираем .exe файл
      - name: Build executable with PyInstaller
        run: pyinstaller --onefile --windowed --name "Adlens_xyzconverter" xyzconverter.py

      # 6. Создаем ZIP-архив с программой
      # Используем встроенную в PowerShell команду Compress-Archive
      - name: Create ZIP from executable
        run: Compress-Archive -Path dist/Adlens_xyzconverter.exe -DestinationPath "Adlen's xyzconverter.zip"

      # 7. Создаем ZIP-архив с исходным кодом
      # Используем * для включения всех файлов и папок, включая .github
      - name: Create ZIP from source code
        run: Compress-Archive -Path * -DestinationPath "source-code.zip"

      # 8. Загружаем оба ZIP-файла как ассеты к релизу
      # Используем популярный action, который делает это автоматически
      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          # Файлы, которые нужно прикрепить к релизу.
          # Каждый файл с новой строки.
          files: |
            Adlen's xyzconverter.zip
            source-code.zip
